### ISSUE TITLE
create release installable directly without compiling

### ISSUE THREAD

**Issue by Grummfy** [Kopano-dev/mattermost-plugin-notifymatters#1]
Hello,
I think it could be good to have release that you can install without compiling this

**Comment by fbartels** [comment]
Hi @Grummfy,

we are providing binary releases of the plugin at https://download.kopano.io/community/mattermost-plugin-notifymatters:/.

**Comment by Grummfy** [comment]
oki, thanks, you should also do it inside github, but OK. Thanks

**Comment by fbartels** [comment]
Hi @Grummfy,

thanks for your feedback. We are mostly "misusing" Github to mirror our code to increase visibility, while the actual development takes place on other systems (self hosted Bitbucket, Jira, Jenkins). I'll make a note to improve the readme here to better guide interested users.
